version: '3'

services:
  elasticsearch:
    build: .
    volumes:
      - esdata:/usr/share/elasticsearch
    environment:
      - discovery.type=single-node
    restart: 'no'
    ports:
      - '9200:9200'
      - '9300:9300'
  logstash:
    image: docker.elastic.co/logstash/logstash:7.1.1
    restart: 'no'
    links:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:7.1.1
    restart: 'no'
    ports:
      - '5601:5601'
    links:
      - elasticsearch
      - logstash

volumes:
  esdata:
    driver: local
