version: '3'

services:
  elasticsearch:
    build: .
    volumes:
      - esdata:/usr/share/elasticsearch
    environment:
      - discovery.type=single-node
    restart: 'no'
    ports:
      - '9200:9200'
      - '9300:9300'
  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.2
    restart: 'no'
    ports:
      - '5601:5601'
    links:
      - elasticsearch

volumes:
  esdata:
    driver: local
